export const cards = [
    {
      id: 1,
      title: "AI Artists",
      desc: "Add talent to AI",
      img: "https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 2,
      title: "Logo Design",
      desc: "Build yor brand",
      img: "https://images.pexels.com/photos/11295165/pexels-photo-11295165.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 3,
      title: "WordPress",
      desc: "Customize your site",
      img: "https://images.pexels.com/photos/4371669/pexels-photo-4371669.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 4,
      title: "Voice Over",
      desc: "Share your message",
      img: "https://images.pexels.com/photos/7608079/pexels-photo-7608079.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 5,
      title: "Video Explainer",
      desc: "Engage your audience",
      img: "https://images.pexels.com/photos/13388047/pexels-photo-13388047.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 6,
      title: "Social Media",
      desc: "Reach more customers",
      img: "https://images.pexels.com/photos/11378899/pexels-photo-11378899.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 7,
      title: "SEO",
      desc: "Unlock growth online",
      img: "https://images.pexels.com/photos/4820241/pexels-photo-4820241.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 8,
      title: "Illustration",
      desc: "Color you dreams",
      img: "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
  ];
  
  export const projects = [
    {
      id: 1,
      img: "https://www.formation-industries-occitanie.fr/wp-content/uploads/2024/03/diplome-ingenieur-cesi-toulouse-1024x574.jpeg",
      pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Réparation des télephones",
      username: "Anas Kassimi",
    },
    {
      id: 2,
      img: "https://f.hellowork.com/obs-static-images/seo/ObsJob/electronicien.jpg",
      pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Réparation des tablettes",
      username: "Youness Alaoui",
    },
    {
      id: 3,
      img: "https://www.novae-recrute.com/storage/jobs/electronicien.jpg",
      pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Réparation des ordinateurs",
      username: "Youssef Chraibi",
    },
    {
      id: 4,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoqbXAx3g524wTJRxviPhdAPjYjecjU70zsqrZKJ7v_D2IlARmicuSakqjQ8m5txDs83A&usqp=CAU",
      pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Réparation des serveurs",
      username: "Rachid Idrissi",
    },
    {
      id: 5,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTunNhGZ7qsdWljiKOfnDG222qiVqDFIRzrLDwTDE2gBjDjuf0dll5jLuD3f037V7o5RwI&usqp=CAU",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Formattage des ordinateurs",
      username: "Omar Bouzid",
    },
    {
      id: 6,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaGTAtS3z-1yPcYhJ1YpboXfS9Z_Oj8cNsbQ&s",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Illustration",
      username: "Karim Tazi",
    },
    {
      id: 7,
      img: "https://f.maformation.fr/edito/sites/3/2020/06/electrotechnicien.jpeg",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Book Design",
      username: "Naima Alaoui",
    },
    {
      id: 8,
      img: "https://us.123rf.com/450wm/wavebreakmediamicro/wavebreakmediamicro1409/wavebreakmediamicro140902017/31312023-sourire-ing%C3%A9nieur-informaticien-travaillant-sur-la-console-cass%C3%A9e-avec-un-tournevis-dans-son.jpg?ver=6",
      pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Digital Marketing",
      username: "Nadia Tazi",
    },
  ];
  
  export const gigs = [
    {
      id: 1,
      img: "https://ichef.bbci.co.uk/ace/ws/640/cpsprodpb/98CC/production/_131761193_1f064d43-afea-4dd9-8743-57e979a4b18b.jpg.webp",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Je réparerai votre tablette et la remettrai comme neuve",
      price: 59,
      star: 5,
      username: "Youssef Chraibi",
    },
    {
      id: 2,
      img: "https://static.vecteezy.com/ti/photos-gratuite/p1/16852270-reparation-et-mise-a-niveau-du-telephone-mobile-de-l-electronique-du-materiel-informatique-et-du-concept-technologique-photo.jpg",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Je réparerai votre téléviseur rapidement et efficacement.",
      price: 79,
      star: 5,
      username: "Rachid Idrissi",
    },
    {
      id: 3,
      img: "https://highservice.ma/wp-content/uploads/2024/02/reparation-electronique-indusrtrielle-.jpg",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Je réparerai votre console de jeux pour que vous puissiez jouer sans interruption",
      price: 112,
      star: 5,
      username: "Omar Bouzid",
    },
    {
      id: 4,
      img: "https://www.actu-environnement.com/images/illustrations/news/35115_large.jpg",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Je réparerai votre ordinateur portable, quelle que soit la marque ou le problème.",
      price: 99,
      star: 4,
      username: "Karim Tazi",
    },
    {
      id: 5,
      img: "https://img.freepik.com/photos-gratuite/reparation-circuits-imprimes-gros-plan_23-2148419130.jpg",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Je réparerai vos appareils électroménagers intelligents.",
      price: 59,
      star: 5,
      username: "Naima Alaoui",
    },
    {
      id: 6,
      img: "https://www.ecosystem.eco/upload/medias/645c9943f030c9.87467322_reparation.jpg",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Je réparerai votre drone pour qu'il soit prêt à voler à nouveau.",
      price: 79,
      star: 4,
      username: "Nadia Tazi ",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Je réparerai votre appareil photo numérique et ses accessoires",
      price: 89,
      star: 5,
      username: "Ahmed Bennis",
    }
   
  ];